### ISSUE TITLE
Build artifacts should have portable canonical name for server and client

### ISSUE THREAD

**Issue by grempe** [int08h/roughenough#10]
The build artifacts:

```
target/release/server
target/release/client
```

Are very generic and most would want to rename them to something more appropriate on all but a server dedicated to only running these artifacts. If you were to install the server and client using a packaging tool such as Homebrew (e.g. `brew install roughtime`) you would also want a more specific name. All such installations, from source or package manager, should use these names.

Perhaps `roughtime-client` and `roughtime-server`?

**Comment by int08h** [comment]
Excellent point!

I renamed the binaries to `roughenough-client` and `roughenough-server` and released v1.0.6 with the change.

**Comment by grempe** [comment]
Excellent. I will use this immediately as I am building a very efficient (85MB with debian-slim OS and the two pre-built binaries) Docker image that will contain *only* the compiled binaries. Now I won't have to rename them!

**Comment by grempe** [comment]
FYI : Here's a link to the latest Dockerfile which builds 1.0.6 binaries into a Docker image ~85MB in size (which only has to be pulled once of course for each release).

https://github.com/chainpoint/chainpoint-roughtime/blob/master/Dockerfile

And here's an example usage, and its output, that anyone with Docker installed can use to run the client (or server) with no need to build or install anything:

```
docker run -it --rm gcr.io/chainpoint-registry/github-chainpoint-chainpoint-roughtime:latest roughenough-client roughtime.int08h.com 2002 -p 016e6e0284d24c37c6e4d7d8d5b4e1d3c1949ceaa545bf875616c9dce0c9bec1

Requesting time from: "roughtime.int08h.com":2002
Received time from server: midpoint="Oct 07 2018 21:44:14", radius=1000000 (merkle_index=0, verified=true)
```
