### ISSUE TITLE
Split KMS functionality into separate optional crates?

### ISSUE THREAD

**Issue by anp** [int08h/roughenough#18]
Hi! I'm working on a PR to bump the version of \*ring\* used in roughenough, but I'm having difficulties building with the versions of the KMS crates which are optional dependencies. The `KmsProvider` trait seems like it could be a good basis for an interface between separate crates, and might even be useful in its own separate crate.

Would you be interested in contributions to split things up a little?

**Comment by int08h** [comment]
Hello @anp! The KMS dependencies do complicate things and I'd welcome work to split things up.

**Comment by int08h** [comment]
Hi @anp. I'm closing the issue as it's stale but continue to welcome a PR or further discussion.

**Comment by anp** [comment]
OK! I’d still like to do this but it’ll be a bit before I can circle back to it again :).
