### ISSUE TITLE
Support base64 public keys

### ISSUE THREAD

**Issue by unrelentingtech** [int08h/roughenough#30]
Some prominent public servers publish pubkeys as base64:

```
% host -t TXT roughtime.cloudflare.com
roughtime.cloudflare.com descriptive text "gD63hSj3ScS+wuOeGrubXlq35N1c5Lby/S+T7MNTjxo="
```

while roughenough currently only supports hex encoded ones:

```
% roughenough-client -p0 roughtime.cloudflare.com 2002 -k "gD63hSj3ScS+wuOeGrubXlq35N1c5Lby/S+T7MNTjxo="
thread 'main' panicked at 'Error parsing public key!: DecodeError { position: 0, kind: Symbol }', src/bin/roughenough-client.rs:384:14
```

They probably should be supported?

[The draft RFC also publishes base64](https://www.ietf.org/archive/id/draft-ietf-ntp-roughtime-05.html#section-9-2) so I'm not actually sure where the hex format came from?

**Comment by lachesis** [comment]
I opened #31 to do this

**Comment by int08h** [comment]
PR #31  has been merged, thank you. 

> The draft RFC also publishes base64](https://www.ietf.org/archive/id/draft-ietf-ntp-roughtime-05.html#section-9-2) so I'm not actually sure where the hex format came from?

My fault. About 5 years ago when I wrote roughenough there wasn't any convention or standard. So I just  used hex in the TXT record. :shrug:
