### ISSUE TITLE
Failed to build on IPv6-only host

### ISSUE THREAD

**Issue by marek22k** [int08h/roughenough#36]
The source code cannot be downloaded on an IPv6-only node and accordingly cannot be compiled.
```sh
$ git clone https://github.com/int08h/roughenough.git
Cloning into 'roughenough'...
fatal: unable to access 'https://github.com/int08h/roughenough.git/': Failed to connect to github.com port 443 after 32 ms: Couldn't connect to server
```
```sh
$ wget "https://github.com/int08h/roughenough/archive/refs/heads/master.zip"
--2023-10-12 18:34:42--  https://github.com/int08h/roughenough/archive/refs/heads/master.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... failed: Network is unreachable.
```
```sh
$ nslookup github.com
Server:		::1
Address:	::1#53

Non-authoritative answer:
Name:	github.com
Address: 140.82.121.3
```

**Comment by int08h** [comment]
Hmm, this doesn't look specific to this project. Seems to be a general issue with the system doing the clone (this should impact anything accessing github). Closing.

**Comment by neuralnexus** [comment]
GitHub does not support IPv6 connectivity for its main `github.com` service endpoints, which are still IPv4 only. You will run into this issue often if you use IPv6-only systems. The best way to solve it is to proxy your clone request through an IPv4 server endpoint.
