### ISSUE TITLE
Implement RFC draft11

### ISSUE THREAD

**Issue by int08h** [int08h/roughenough#40]
Adds a new tag `SRV` and verification process. 

Ref Cloudflare implementation tracking issue https://github.com/cloudflare/roughtime/issues/53 for draft11 (was draft10)

**Comment by cjpatton** [comment]
Just a heads up that we've merged support for draft 10: https://github.com/cloudflare/roughtime/pull/55

I'll update here once we have it deployed.

**Comment by cjpatton** [comment]
@wbl bumped draft 11 to fix an ambiguity, so we're taking draft 11 instead of 10: https://github.com/cloudflare/roughtime/pull/57

**Comment by int08h** [comment]
Ack. Looking at draft11 now.

**Comment by int08h** [comment]
@cjpatton  Draft 11 updates merged. I updated the server `roughtime.int08h.com:2002` to run the update.

**Comment by vserdyuk** [comment]
Hello

Do you have plans for TCP server support as required by the draft-10? Unfortunately, Cloudflare's project doesn't have plans for this: https://github.com/cloudflare/roughtime/issues/53#issuecomment-2598576943

**Comment by int08h** [comment]
@vserdyuk I do not have plans to implement TCP transport in the Roughenough server. Client also no plans to implement TCP at this time. 

I'll wait and see how the usage of roughtime evolves in the ecosystem and revisit the TCP-or-not decision a little later.
