### ISSUE TITLE
Bump untrusted for security

### ISSUE THREAD

**Issue by tirkarthi** [int08h/roughenough#6]
Hi,

This project seems to use `untrusted = 0.5` as I can see from the cargo.toml file on master branch. Recently a security issue was fixed as part of 0.6.2 release. Please refer to https://github.com/RustSec/advisory-db/commit/3c0458d26bd19e30dc19ae5ca9a4540cc9c0394b . 

Kindly ignore if this is irrelevant or fixed on another branch.

Thanks.

**Comment by int08h** [comment]
Thank you @tirkarthi, I've updated to `untrusted` to 0.6 and will make a new release.
